import { registerBlock } from '../services/block-service';


const blocks = [
  {
    id: '29f856fe-11d2-426b-b68d-90480257c994',
    type: 'page',
    properties: {},
    content: [
      '12133a9a-3d9f-4b61-bd5c-bf4d05718869',
      '1d99ac24-65ae-410d-bf75-d83fc6a12f15',
      '38f0ac4f-d17c-4ea1-ac41-f6002a2afbbf',
      '0ce0eb27-52c9-417c-9835-d729c8049588',
      '2ee73e2a-dfa1-4a9f-b1b1-0c3d47052907',
    ],
  },
  {
    id: '12133a9a-3d9f-4b61-bd5c-bf4d05718869',
    type: 'h2',
    properties: {
      text: 'Four Corners Vintage'
    },
    content: [],
  },
  {
    id: '1d99ac24-65ae-410d-bf75-d83fc6a12f15',
    type: 'paper',
    properties: {
      elevation: 3,
      padding: '5px',
      width: '75%',
      backgroundColor: 'black',
    },
    content: ['5df82f2a-2c0f-454c-9de3-f363fae61627'],
  },
  {
    id: '5df82f2a-2c0f-454c-9de3-f363fae61627',
    type: 'image',
    properties: {
      path: '/static/collections/4c_banner.png',
      width: '100%',
      height: 'auto',
    },
    content: [],
  },
  {
    id: '38f0ac4f-d17c-4ea1-ac41-f6002a2afbbf',
    type: 'paper',
    properties: {
      elevation: 3,
      padding: '10px',
      margin: '10px',
    },
    content: ['ede68c8c-904f-4250-942c-3d10fa66904f'],
  },
  {
    id: 'ede68c8c-904f-4250-942c-3d10fa66904f',
    type: 'text',
    properties: {
      text: '*Four Corners Vintage starts with a black filled background where four randomized colors at each corner starts and gently fades away as far as you go from it creating a gradient effect which is them framed by a nice and beautiful golden border.*',
      margin: '10px 0',
      align: 'justify',
    },
    content: [],
  },
  {
    id: '0ce0eb27-52c9-417c-9835-d729c8049588',
    type: 'container',
    properties: {
      maxWidth: 'sm',
    },
    content: [
      'bd717c36-6ffb-4523-b6d3-17acce44f8bc',
      '5924407a-a55e-4ea6-85b5-c34c5e0c1954',
      '23792262-07ac-4962-b29f-6893bfec20af',
      '6e08ae59-eed0-435c-9271-0f8fb850e276',
      'be40ea98-f506-49cd-90d8-41ff2b47c481',
      '50474246-0f95-40ea-8e00-0f4e4e066afc',
      '3aaa7ac6-89e3-4665-ad72-99d28384c9ad',
      '2b468067-9cab-40a3-a772-d7f2b8b800a6',
      '0d0d4c62-c473-4779-8b9c-60193e5539ad',
      'e2f503e8-f8e9-41f3-8be5-cbc134d5d753',
      '451b5be4-ba7d-41bd-9035-db1ffa8917fc',
      'cde9319c-4ecf-4ed2-85a4-a5535b46094d',
      '5b29031f-fdd9-45da-b9c7-419f5b583e57',
      'f7aa7cdf-d874-4b6b-a53c-55b91dd3e216',
      'b84061b1-aba5-47a7-a8c4-1aa1ab237c3a',
      '52787927-f9cb-492e-ab70-5b58e834e804',
      '26874c4e-2de8-4c21-83bc-79045f42365b',
      '92a8c07a-98ae-4a03-87bc-67c652f19ac0',
      '2e6dd0ab-22fe-4136-b688-f2d374157209',
    ],
  },
  {
    id: 'bd717c36-6ffb-4523-b6d3-17acce44f8bc',
    type: 'text',
    properties: {
      text: '**Four Corners Vintage** started with the concept of combining gradients, by those means we developed the first two building blocks **Pixel Paint** and **Color Interpolation.**',
      align: 'justify',
    },
    content: [],
  },
  {
    id: '5924407a-a55e-4ea6-85b5-c34c5e0c1954',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/gradient.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '23792262-07ac-4962-b29f-6893bfec20af',
    type: 'subtitle',
    properties: {
      text: 'Gradient generated by "Pixel Paint" and "Color Interpolation" building blocks'
    },
    content: [],
  },
  {
    id: '6e08ae59-eed0-435c-9271-0f8fb850e276',
    type: 'text',
    properties: {
      text: 'The first idea was creating individual randomized gradient colors, rotating and combining them using transparent layers.',
      align: 'justify'
    },
    content: [],
  },
  {
    id: 'be40ea98-f506-49cd-90d8-41ff2b47c481',
    type: 'stack',
    properties: {
      direction: 'row',
      spacing: 2,
    },
    content: [
      '807e820e-5729-4e1c-9c2f-c6c5f0a4f376',
      'f3106a61-2767-4825-8e12-f04d440e6447',
      '1d16db03-16e0-4c83-a7ca-69e6c5797007',
      '9716e807-fa87-49b1-b041-f5fc74fe3f0f',
    ],
  },
  {
    id: '807e820e-5729-4e1c-9c2f-c6c5f0a4f376',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p0.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: 'f3106a61-2767-4825-8e12-f04d440e6447',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p1.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '1d16db03-16e0-4c83-a7ca-69e6c5797007',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p2.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '9716e807-fa87-49b1-b041-f5fc74fe3f0f',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p3.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '50474246-0f95-40ea-8e00-0f4e4e066afc',
    type: 'subtitle',
    properties: {
      text: 'Individual gradient layers rotated by "Rotation" building block'
    },
    content: [],
  },
  {
    id: '3aaa7ac6-89e3-4665-ad72-99d28384c9ad',
    type: 'text',
    properties: {
      text: 'This is where the first problem arised, the layers order mattered and the last one was proeminent in image because it overlaps 2 corners:'
    },
    content: [],
  },
  {
    id: '2b468067-9cab-40a3-a772-d7f2b8b800a6',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/overlap.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '0d0d4c62-c473-4779-8b9c-60193e5539ad',
    type: 'subtitle',
    properties: {
      text: 'Resulting image, note the predominance of the last purple gradient'
    },
    content: [],
  },
  {
    id: 'e2f503e8-f8e9-41f3-8be5-cbc134d5d753',
    type: 'text',
    properties: {
      text: 'At this point we decided to try another approach though it looked nice but not enough, at least we knew that we were in the right direction. One considered option was implementing another core block called **Blend Modes**, but at the end we kept it for future releases and choose an approach that didn\'t have overlapping, this is where the four corners concept was born.',
      align: 'justify',
    },
    content: [],
  },
  {
    id: '451b5be4-ba7d-41bd-9035-db1ffa8917fc',
    type: 'text',
    properties: {
      text: 'We still generate four gradients with randomize colors but starting from a single corner, rotate each one by a multiple of 90 degrees, resulting in four different images with a gradient on each corner:',
      align: 'justify',
    },
    content: []
  },
  {
    id: 'cde9319c-4ecf-4ed2-85a4-a5535b46094d',
    type: 'stack',
    properties: {
      direction: 'row',
      spacing: 2,
    },
    content: [
      '09a9720b-569a-4b92-b71e-4fc1138b4cbd',
      '95439cbd-61c4-44b3-9a08-6ea692f1a1c1',
      'f9def2a3-4e6e-4333-a112-5408da12f738',
      'c3308b1b-ea3f-4a8e-a021-d6e3c82b485f',
    ]
  },
  {
    id: '09a9720b-569a-4b92-b71e-4fc1138b4cbd',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_p0.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '95439cbd-61c4-44b3-9a08-6ea692f1a1c1',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_p1.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: 'f9def2a3-4e6e-4333-a112-5408da12f738',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_p2.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: 'c3308b1b-ea3f-4a8e-a021-d6e3c82b485f',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_p3.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '5b29031f-fdd9-45da-b9c7-419f5b583e57',
    type: 'subtitle',
    properties: {
      text: 'Individual corner gradient layers rotated by "Rotation" building block'
    },
    content: [],
  },
  {
    id: 'f7aa7cdf-d874-4b6b-a53c-55b91dd3e216',
    type: 'text',
    properties: {
      text: 'As minting lots of NFTs is not a simple task, we started simple by manually minting a small amount of them. As we created few artwork, we needed something to make them special, this is where the golden border and vintage concept arise.',
      align: 'justify',
    },
    content: [],
  },
  {
    id: 'b84061b1-aba5-47a7-a8c4-1aa1ab237c3a',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_p4.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '52787927-f9cb-492e-ab70-5b58e834e804',
    type: 'subtitle',
    properties: {
      text: 'Golden border',
    },
    content: [],
  },
  {
    id: '26874c4e-2de8-4c21-83bc-79045f42365b',
    type: 'text',
    properties: {
      text: 'Wrapping everything up, when we combine all of them with a black background, they\'d look like the following image:',
      align: 'justify',
    },
    content: [],
  },
  {
    id: '92a8c07a-98ae-4a03-87bc-67c652f19ac0',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/4c_example.png',
      width: '150px',
      height: 'auto'
    },
    content: [],
  },
  {
    id: '2e6dd0ab-22fe-4136-b688-f2d374157209',
    type: 'subtitle',
    properties: {
      text: 'Resulting image using "Layers" building block',
    },
    content: [],
  },
  {
    id: '2ee73e2a-dfa1-4a9f-b1b1-0c3d47052907',
    type: 'box',
    properties: {
      width: '100%',
      flex: {
        direction: 'column',
      }
    },
    content: [
      '8d35d64f-6f2f-46e3-a2f1-d381c26c6fb5',
      '860512f7-6615-4f62-9a05-df41737fb69b',
      '3efd0dba-e721-4c2b-9d8b-97b02c99a836',
      '6f83046f-5bad-4925-a10c-e73e52267a24',
    ],
  },
  {
    id: '8d35d64f-6f2f-46e3-a2f1-d381c26c6fb5',
    type: 'text',
    properties: {
      text: 'Thanks for coming with us through our entire collection'
    },
    content: [],
  },
  {
    id: '860512f7-6615-4f62-9a05-df41737fb69b',
    type: 'text',
    properties: {
      text: 'concept process and stay tuned for our next release.'
    },
    content: [],
  },
  {
    id: '3efd0dba-e721-4c2b-9d8b-97b02c99a836',
    type: 'available-on-open-sea',
    properties: {
      target: 'collection/4-corners-vintage',
    },
    content: [],
  },
  {
    id: '6f83046f-5bad-4925-a10c-e73e52267a24',
    type: 'text',
    properties: {
      text: 'OutOfMemory NFT team.'
    },
    content: [],
  }
];

blocks.forEach((block) => registerBlock(block.id, block));


const staticUuids = [
  
  
  
  
  '8fc808ec-19a4-4d46-9509-fdd146bb5c3c',
];