import defaults from './defaults';

const _blocks = [
  {
    id: 'e48a4084-8304-4b09-8e66-0fa0544428f4',
    type: 'text',
    properties: {
      text: 'For the animated border, we first generate a list of points and group them in a way that each group represents a small bar of the border:',
      ...defaults.text,
    },
    content: [],
  },
  {
    id: 'ff054b8f-73b9-4b24-ae4d-bc9b6288a5f2',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p0.png',
      ...defaults.image,
    },
    content: [],
  },
  {
    id: 'e979afa9-899c-4ed6-9b59-3d1f0ddc736e',
    type: 'subtitle',
    properties: {
      text: 'Group of points to draw border',
      ...defaults.subtitle,
    },
    content: [],
  },
  {
    id: '56740e01-624c-4135-a493-9aa6777c2312',
    type: 'text',
    properties: {
      text: 'So it\'s a matter of selecting X groups each frame where each group is painted with a color generated by the **Color** Interpolation** the same way that we create a fading circle, we create a fading bar',
      ...defaults.text,
    },
    content: [],
  },
  {
    id: '2103a35d-0865-4d55-b295-011246a85b5d',
    type: 'stack',
    properties: {
      ...defaults.stack,
    },
    content: [
      'da4897aa-99e0-464f-9620-b8cc51a47f34',
    ],
  },
  {
    id: 'da4897aa-99e0-464f-9620-b8cc51a47f34',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p0.png',
      ...defaults.image,
    },
    content: [],
  },
  {
    id: 'f27ecb15-f17f-411c-bd6a-115bdc0fdf1f',
    type: 'subtitle',
    properties: {
      text: 'Frames of animated border',
      ...defaults.subtitle,
    },
    content: [],
  },
  {
    id: 'c1a25c00-cc50-4984-9166-bca3fb3a33fc',
    type: 'text',
    properties: {
      text: 'Also using **Layers** and **Gif** we generate individual layers to combine later on in the resulting gif:',
      ...defaults.text,
    },
    content: [],
  },
  {
    id: 'ab70f989-9a59-47d6-9235-26cdeaecbcc2',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p0.png',
      ...defaults.image,
    },
    content: [],
  },
  {
    id: 'a125b764-2668-46b8-b829-cde52501382f',
    type: 'subtitle',
    properties: {
      text: 'Border animated',
      ...defaults.subtitle,
    },
    content: [],
  },
  {
    id: '361edf94-416a-4543-aeb2-2135831e8dc3',
    type: 'text',
    properties: {
      text: 'Having all pieces, we can use the **Merge** building block to combine each individual frame at X and them create our final and beautiful NFT:',
      ...defaults.text,
    },
    content: [],
  },
  {
    id: '4ce7e597-2ad1-459d-9636-56a87b907504',
    type: 'image',
    properties: {
      path: '/static/collections/four-corners/problem_p0.png',
      ...defaults.image,
    },
    content: [],
  },
  {
    id: '3dde8592-778b-4389-b965-8ad38bf9ab08',
    type: 'subtitle',
    properties: {
      text: 'Waves with border combined using Merge',
      ...defaults.subtitle,
    },
    content: [],
  },
];